### ISSUE TITLE
i.size is not a function

### ISSUE THREAD

**Issue by Akeem832** [ctsit/imagemap#22]
Could there be an issue with this module on REDCap 8.10.16 / 8.10.17?
Using the included example dictionary, only the first imagemap is displayed and the console gives:

> Uncaught TypeError: i.size is not a function
>     at HTMLImageElement.<anonymous> (index.php?pid=104&id=1&event_id=366&page=imagemap_examples_fd0788&auto=1:900)
>     at Function.each (base.js:6)
>     at w.fn.init.each (base.js:6)
>     at w.fn.init.me.bind (index.php?pid=104&id=1&event_id=366&page=imagemap_examples_fd0788&auto=1:900)
>     at w.fn.init.$.fn.mapster (index.php?pid=104&id=1&event_id=366&page=imagemap_examples_fd0788&auto=1:900)
>     at Object.imageMapEM.render (imagemap.js?1558950415:146)
>     at Object.<anonymous> (imagemap.js?1558950415:44)
>     at Function.each (base.js:6)
>     at HTMLDocument.<anonymous> (imagemap.js?1558950415:41)
>     at l (base.js:6)

**Comment by marlycormar** [comment]
Hi @Akeem832, thank you for reaching out. Which version of imagemap are you using? The issue you are mentioning was fixed on v1.2.2. Please ask your REDCap administrator to enable the latest imagemap **v1.4.0** found [here](https://redcap.vanderbilt.edu/consortium/modules/index.php).

**Comment by Akeem832** [comment]
I'm actually using Image Map - v1.4.0.

**Comment by marlycormar** [comment]
@Akeem832 can you send us an example so that we can reproduce your issue? An instrument/project will work.

**Comment by marlycormar** [comment]
@Akeem832 the module is having issues with older versions of REDCap, which may be causing yours as well. Let me downgrade my testing environment and try to reproduce your issue.

**Comment by Akeem832** [comment]
I used the **Instrument Example.zip** from https://github.com/ctsit/imagemap/tree/master/docs. I used this on 8.10.16,17 and 8.10.18, so the lastest LTS, not an older version of REDCap

**Comment by pbchase** [comment]
@Akeem832 I double checked this for Marly. Every reference to "i.size" was removed from our code at version 1.2.2. The error message you are receiving is from Imagemap 1.2.1 or earlier. I encourage you to upgrade to ImageMap 1.4.1, recently released in the REDCap Repo.  It includes the fixes released in ImageMap 1.2.2.

**Comment by Akeem832** [comment]
Hi,
The issue remains on REDCap 9.1.10 with imagemap 1.4.2:
https://photos.app.goo.gl/QZxk4yiN4Nz1KrXA9
The screenshot shows the versions used.

This is with the Imagemap Example instrument from here: https://github.com/ctsit/imagemap/blob/master/docs/Instrument%20Example.zip


base.js:6 Uncaught TypeError: i.size is not a function
    at HTMLImageElement.<anonymous> (index.php?pid=140&id=1&event_id=598&page=imagemap_examples&auto=1:936)
    at Function.each (base.js:6)
    at k.fn.init.each (base.js:6)
    at k.fn.init.me.bind (index.php?pid=140&id=1&event_id=598&page=imagemap_examples&auto=1:936)
    at k.fn.init.$.fn.mapster (index.php?pid=140&id=1&event_id=598&page=imagemap_examples&auto=1:936)
    at Object.imageMapEM.render (imagemap.js?1567609826:146)
    at Object.<anonymous> (imagemap.js?1567609826:44)
    at Function.each (base.js:6)
    at HTMLDocument.<anonymous> (imagemap.js?1567609826:41)
    at e (base.js:6)

**Comment by pbchase** [comment]
@taylorr4, @ChemiKyle, could you take a look at the screenshots in @Akeem832's last comment? They show the error he is reporting in a minified copy of JQuery on line 6 of `redcap_v9.1.1/Resources/js/base.js`. I'm not sure how his install of the imagemap module is loading your JQuery, but that appears to be the case. We fixed our reference to i.size in this commit: https://github.com/ctsit/imagemap/commit/75d85e53c0a5e650dd2fe4540f76096857384470

What do you think is happening here?

**Comment by taylorr4** [comment]
@pbchase very strange. For REDCap, we usually wrap any jQuery code in `$(function(){ });` rather than using `(function(){ })()`. Do you think that is causing it? Does `(function(){ })()` wait for document ready, which is required by jQuery code?

**Comment by Akeem832** [comment]
The issue was caused by the legacy imagemap hook which was still enabled on this machine.
The imagemap external module works as expected when disabling the hook(s).

**Comment by pbchase** [comment]
Thanks for letting us know, @Akeem832. I wish I could say that had never happened to me.
